import { SiderBar } from '@/components/SiderBar'
import '@/app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './header'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=' antialiased'>
      <body className={inter.className}>
       <div className='grid min-h-screen grid-cols-app'>
        
        <SiderBar />
        <main className=' px-4 pt-8'>
          <Header />
          

          {children}
          </main>
        
       
        </div> 
        </body>
    </html>
  )
}
